### ISSUE TITLE
Can't get blob and longblob data using MySQL

### ISSUE THREAD

**Issue by unleed-l** [insinfo/eloquent_dart#3]
When i try to get blob and longblob data from MySQL database the following error occurs:

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FormatException: Invalid UTF-8 byte (at offset 0)
#0      MySQLConnection._executePreparedStmt.<anonymous closure> (package:mysql_client/src/mysql_client/connection.dart:1033:47)
#1      MySQLConnection._processCommandResponse (package:mysql_client/src/mysql_client/connection.dart:433:23)
#2      MySQLConnection._processSocketData (package:mysql_client/src/mysql_client/connection.dart:273:7)
#3      MySQLConnection.connect.<anonymous closure> (package:mysql_client/src/mysql_client/connection.dart:125:9)
#4      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365:11)
#6      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297:7)
#7      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#8      _StreamController._add (dart:async/stream_controller.dart:658:7)
#9      _StreamController.add (dart:async/stream_controller.dart:606:5)
#10     _Socket._onData (dart:io-patch/socket_patch.dart:2455:41)
#11     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#12     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365:11)
#13     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297:7)
#14     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#15     _StreamController._add (dart:async/stream_controller.dart:658:7)
#16     _StreamController.add (dart:async/stream_controller.dart:606:5)
#17     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1942:33)
#18     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1385:14)
#19     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#20     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```

**Comment by insinfo** [comment]
This problem is not with eloquent but with the mysql driver and should be reported in the driver repository

https://github.com/zim32/mysql.dart

**Comment by unleed-l** [comment]
> This problem is not with eloquent but with the mysql driver and should be reported in the driver repository
> 
> https://github.com/zim32/mysql.dart

This repository seems to no longer be updated, do you have any idea how to fix this ourselves?

**Comment by insinfo** [comment]
I use this package in all projects I work on day to day, I use it mostly with PostgreSQL, I've been quite busy at work and I haven't had time to improve the documentation. 

I'm improving test coverage for postgresql, if you want to contribute tests for mysql I would be very grateful

**Comment by unleed-l** [comment]
> I use this package in all projects I work on day to day, I use it mostly with PostgreSQL, I've been quite busy at work and I haven't had time to improve the documentation. 
> 
> I'm improving test coverage for postgresql, if you want to contribute tests for mysql I would be very grateful 

Oh, thanks for answer!
I'm no longer working on this project and MySQL database, but i can help you with your tests if you need.
